# Generated by Django 3.0.6 on 2020-05-31 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_desc', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SizeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.IntegerField()),
                ('size_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_sub_desc', models.CharField(max_length=60)),
                ('menu_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.MenuOption')),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_dec', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenuOptionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='0.0', max_digits=3)),
                ('menusuboption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.SubMenuOption')),
                ('munusuboptionsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.SizeDetail')),
            ],
        ),
    ]
