# Generated by Django 3.0.6 on 2020-05-31 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0002_menuoption_sizedetail_submenuoption_submenuoptiondetail_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizedetail',
            name='size_type',
        ),
    ]
