# Generated by Django 3.0.6 on 2020-05-31 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0003_remove_sizedetail_size_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenuoptiondetail',
            old_name='munusuboptionsize',
            new_name='menusuboptionsize',
        ),
    ]
