# Generated by Django 3.0.6 on 2020-05-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0004_auto_20200531_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenuoptiondetail',
            name='price',
            field=models.TextField(),
        ),
    ]
