# Generated by Django 3.0.6 on 2020-06-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0006_submenuoptiondetail_toppingsallowed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.AddField(
            model_name='submenuoptiondetail',
            name='numberOfToppings',
            field=models.IntegerField(default=0),
        ),
    ]
