# Generated by Django 3.0.6 on 2020-06-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0008_auto_20200605_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenuoption',
            name='toppingsallowed',
        ),
        migrations.RemoveField(
            model_name='submenuoptiondetail',
            name='numberOfToppings',
        ),
        migrations.AddField(
            model_name='submenuoption',
            name='numberOfToppings',
            field=models.IntegerField(default=0),
        ),
    ]
