# Generated by Django 3.0.6 on 2020-06-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0010_auto_20200605_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='menu_option',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='price',
        ),
        migrations.AlterField(
            model_name='submenuoptiondetail',
            name='price',
            field=models.TextField(),
        ),
    ]
