# Generated by Django 3.0.6 on 2020-06-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0011_auto_20200605_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuoption',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
