# Generated by Django 3.0.6 on 2020-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0012_submenuoption_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoption',
            name='contains_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submenuoptiondetail',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
