# Generated by Django 3.0.6 on 2020-06-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0015_extratoppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenuoption',
            name='extra',
        ),
    ]
