# Generated by Django 3.0.6 on 2020-06-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0016_remove_submenuoption_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratoppings',
            name='menu_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.MenuOption'),
        ),
    ]
