# Generated by Django 3.0.6 on 2020-06-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0017_extratoppings_menu_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratoppings',
            name='toping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.Toppings'),
        ),
    ]
