# Generated by Django 3.0.6 on 2020-06-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0018_auto_20200606_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extratoppings',
            old_name='toping',
            new_name='topping',
        ),
    ]
