# Generated by Django 3.0.6 on 2020-06-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0020_auto_20200606_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extratoppings',
            name='extra_topping_dec',
        ),
        migrations.AddField(
            model_name='extratoppings',
            name='parentTopping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_topping', to='pizza_shop.Toppings'),
        ),
        migrations.AddField(
            model_name='toppings',
            name='isextra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extratoppings',
            name='menu_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.MenuOption'),
        ),
        migrations.AlterField(
            model_name='extratoppings',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.Toppings'),
        ),
    ]
