# Generated by Django 3.0.6 on 2020-06-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0024_auto_20200606_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppings',
            old_name='topping_dec',
            new_name='topping_desc',
        ),
    ]
