# Generated by Django 3.0.6 on 2020-06-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0025_auto_20200606_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
