# Generated by Django 3.0.6 on 2020-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0026_toppings_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratoppings',
            name='extra_desc',
            field=models.CharField(default='', max_length=60),
        ),
    ]
