# Generated by Django 3.0.6 on 2020-06-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0027_extratoppings_extra_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extratoppings',
            name='extra_desc',
        ),
    ]
