# Generated by Django 3.0.6 on 2020-06-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0028_remove_extratoppings_extra_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extratoppings',
            name='menu_option',
        ),
        migrations.RemoveField(
            model_name='extratoppings',
            name='parentTopping',
        ),
        migrations.RemoveField(
            model_name='extratoppings',
            name='topping',
        ),
        migrations.CreateModel(
            name='ExtraToppingsMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extratopping_desc', models.CharField(max_length=60)),
                ('menu_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.MenuOption')),
                ('parent_topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.Toppings')),
            ],
        ),
        migrations.AddField(
            model_name='extratoppings',
            name='extratoppingmeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.ExtraToppingsMeta'),
        ),
    ]
