# Generated by Django 3.0.6 on 2020-06-08 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza_shop', '0030_auto_20200607_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=400)),
                ('orderplace', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenuprice', models.FloatField(default=0.0)),
                ('submenudesc', models.CharField(max_length=60)),
                ('menudesc', models.CharField(max_length=60)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.Order')),
                ('submenuoptiondetail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pizza_shop.SubMenuOptionDetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrderToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingdesc', models.CharField(max_length=60)),
                ('orderdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.OrderDetail')),
                ('toppingid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pizza_shop.Toppings')),
            ],
        ),
        migrations.CreateModel(
            name='OrderExtraTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extratoppingdesc', models.CharField(max_length=60)),
                ('extratoppingprice', models.FloatField(default=0.0)),
                ('extratoppingid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pizza_shop.ExtraToppings')),
                ('orderdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.OrderDetail')),
            ],
        ),
    ]
