# Generated by Django 3.0.6 on 2020-06-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0031_order_orderdetail_orderextratopping_ordertoppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='orderid',
            new_name='orderdetail',
        ),
    ]
