# Generated by Django 3.0.6 on 2020-06-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0032_auto_20200607_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='orderdetail',
            new_name='orderid',
        ),
    ]
