# Generated by Django 3.0.6 on 2020-06-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0033_auto_20200607_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(default='', max_length=60),
        ),
    ]
