# Generated by Django 3.0.6 on 2020-06-09 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0034_orderdetail_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 8, 23, 1, 38, 464207)),
        ),
    ]
