# Generated by Django 3.0.6 on 2020-06-14 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0035_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 14, 17, 58, 58, 347801)),
        ),
        migrations.AlterField(
            model_name='submenuoption',
            name='toppingsAllowed',
            field=models.BooleanField(default=False),
        ),
    ]
