# Generated by Django 3.0.6 on 2020-06-14 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0036_auto_20200614_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderplace',
            new_name='orderplaced',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 14, 18, 16, 15, 561508)),
        ),
    ]
