# Generated by Django 3.0.6 on 2020-09-05 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0037_auto_20200614_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 5, 10, 5, 8, 492368)),
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.CharField(max_length=60)),
                ('test123', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_shop.OrderExtraTopping')),
            ],
        ),
    ]
